const EntryData = [
	{
		title: "Frist step to Healing",
		description:
			"Last Saturday, I woke up with the sun shining brightly through my window, and I knew it was the perfect day for a trip to the beach. I packed my bag with essentials: sunscreen, a towel, a good book, and a picnic lunch. With excitement bubbling inside me, I hopped into my car and drove towards the shimmering coastline.As I arrived, the sound of crashing waves greeted me, and the salty breeze filled the air. The beach was alive with families enjoying the sun, children building sandcastles, and surfers riding the waves. I found a cozy spot on the warm sand and laid out my towel, feeling the grains slip between my fingers.After applying sunscreen, I took a refreshing dip in the ocean. The water was cool and invigorating, a perfect contrast to the heat of the day. I floated on my back, gazing up at the clear blue sky, feeling completely at peace.Later, I settled down with my book, but I couldn't help but be distracted by the laughter and chatter around me. I watched as a group of friends played beach volleyball, their energy infectious. Eventually, I joined in, and we spent the afternoon laughing and enjoying the friendly competition.As the sun began to set, painting the sky with shades of orange, pink, and purple, I laid back on my towel, savoring the moment. I pulled out my picnic lunch, enjoying fresh fruit and sandwiches while listening to the soothing sounds of the waves.Asday drew to a close, I took a final stroll along the shore, collecting seashells and reflecting on the joy of the day. The beach always had a way of rejuvenating my spirit, and I drove home with a heart full of happiness and a promise to return soon.",
	},

	{
		title: "A Day in the Forest",
		description:
			"Last weekend, I decided to take a break from the hustle and bustle of city life and go for a hike in the nearby forest. As I stepped onto the trail, the cool breeze greeted me, carrying the fresh scent of pine and damp earth. The sunlight filtered through the leaves, creating a beautiful mosaic of light and shadow on the ground.As I walked deeper into the woods, I could hear the chirping of birds and the rustling of small animals in the underbrush. I spotted a family of deer grazing quietly in a clearing. They looked up at me with curiosity but quickly returned to their meal, unfazed by my presence.After an hour of hiking, I reached a serene lake nestled among the trees. The water was crystal clear, reflecting the blue sky above. I sat on a rock by the shore, taking in the peaceful surroundings. I pulled out my sketchbook and began to draw the scenery, capturing the beauty of nature on paper.As the sun began to set, painting the sky in hues of orange and pink, I realized how rejuvenating this escape had been. I packed up my things and headed back, feeling grateful for the beauty of the natural world and the tranquility it brought.",
	},
	{
		title: "A Day in the Forest",
		description:
			"Last weekend, I decided to take a break from the hustle and bustle of city life and go for a hike in the nearby forest. As I stepped onto the trail, the cool breeze greeted me, carrying the fresh scent of pine and damp earth. The sunlight filtered through the leaves, creating a beautiful mosaic of light and shadow on the ground.As I walked deeper into the woods, I could hear the chirping of birds and the rustling of small animals in the underbrush. I spotted a family of deer grazing quietly in a clearing. They looked up at me with curiosity but quickly returned to their meal, unfazed by my presence.After an hour of hiking, I reached a serene lake nestled among the trees. The water was crystal clear, reflecting the blue sky above. I sat on a rock by the shore, taking in the peaceful surroundings. I pulled out my sketchbook and began to draw the scenery, capturing the beauty of nature on paper.As the sun began to set, painting the sky in hues of orange and pink, I realized how rejuvenating this escape had been. I packed up my things and headed back, feeling grateful for the beauty of the natural world and the tranquility it brought.",
	},
	{
		title: "A Day in the Forest",
		description:
			"Last weekend, I decided to take a break from the hustle and bustle of city life and go for a hike in the nearby forest. As I stepped onto the trail, the cool breeze greeted me, carrying the fresh scent of pine and damp earth. The sunlight filtered through the leaves, creating a beautiful mosaic of light and shadow on the ground.As I walked deeper into the woods, I could hear the chirping of birds and the rustling of small animals in the underbrush. I spotted a family of deer grazing quietly in a clearing. They looked up at me with curiosity but quickly returned to their meal, unfazed by my presence.After an hour of hiking, I reached a serene lake nestled among the trees. The water was crystal clear, reflecting the blue sky above. I sat on a rock by the shore, taking in the peaceful surroundings. I pulled out my sketchbook and began to draw the scenery, capturing the beauty of nature on paper.As the sun began to set, painting the sky in hues of orange and pink, I realized how rejuvenating this escape had been. I packed up my things and headed back, feeling grateful for the beauty of the natural world and the tranquility it brought.",
	},
];
export default EntryData;
